### PR TITLE
Support for Jigsaw (JDK9 and up)

### PR DESCRIPTION
**Pull request by aquator**
Add support for JDK9 and by fixing profile activation for pre-jigsaw tools.jar and classes.jar
Plugins and libraries are also updated to support JDK9

In current form the LibDocMojoTest fails, see Issue https://github.com/robotframework/robotframework/issues/2854 and PR https://github.com/robotframework/robotframework/pull/2853

All tests pass with robotframework dependency containing the above fix.

Checked with
- openjdk version "10.0.1" 2018-04-17
  OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
- java version "9.0.4"
  Java(TM) SE Runtime Environment (build 9.0.4+11)
- java version "1.8.0_171"
  Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

### CODE REVIEW

**Comment by cristiadu** [comment]
@jussimalinen I'm sorry to bother you with that, but is this planned to be merged? It's blocking myself from changing my project's version to java 10

**Comment by aquator** [comment]
Hi,

I am waiting for @pekkaclark to merge the changes in robotframework first, then I’ll revisit this one - probably only a version bump is required then.

**Comment by cristiadu** [comment]
But we will still need a new version of this one, right?

**Comment by aquator** [comment]
Nah, some changes will be needed due to handling the non-existent jars. Will do a cleanup on this once the release of RobotFramework is happened (expected today)

**Comment by Hi-Fi** [comment]
I think those test poms doesn't need any changes (just use develop ones), as the test library also was changed and version changed dynamic one. So only main pom.xml needs some work.

**Comment by aquator** [comment]
Is there any trick with MavenLibrary.version? for me locally it fails due to that.

**Comment by Hi-Fi** [comment]
That MavenLibrary.version should come as environment variable from main pom to test ones, so it dynamically tests the latest one. 

Newer jdks can also be tested on travis (https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images)

**Comment by aquator** [comment]
At this point I have no clue whats wrong with travis, command `mvn --settings .travis/settings.xml clean install -B -V -Dgpg.skip -Dmaven.javadoc.skip=true` works fine on my linux with oracle java 8 and maven 3.6 (thats a difference though) I'll keep investigating and report back. Failure on jdk11 is fine since the source and target versions can't work with that in current form.

**Comment by aquator** [comment]
At least it is not maven version. Can you give a hint what is going on? Seems to be failing on missing something that should not be there... Also I wonder why passing on my metal.

**Comment by aquator** [comment]
> That MavenLibrary.version should come as environment variable from main pom to test ones, so it dynamically tests the latest one.

Needed to change that. Strange that actually worked, as that is not the way to use environment variables in Maven. Also it is a good idea to have them in full caps, so it'll work on different OS-es.

**Comment by Hi-Fi** [comment]
> At this point I have no clue whats wrong with travis, command `mvn --settings .travis/settings.xml clean install -B -V -Dgpg.skip -Dmaven.javadoc.skip=true` works fine on my linux with oracle java 8 and maven 3.6 (thats a difference though) I'll keep investigating and report back. Failure on jdk11 is fine since the source and target versions can't work with that in current form.

I think there might be some issue with the tests, or somehow the copying is failing just time to time. Trying to reproduce that with local travis container might be only way forward. I think I have seen that error earlier, too, but that time next run made things work fine.

**Comment by aquator** [comment]
> Or some version update making something to work differently?

Thats my hunch too, will come back to this, and update you latest Monday. If you have time to review the other stuff that would be nice. Still need to tweak the source and target versions, but that can be done with profiling I guess, or simply just not compile with jdk11

**Comment by aquator** [comment]
Getting better, I think I've found the problem. Tweaking further jdk11, I am dropping jdk7 support for now (of course we can put stuff back, but I think is is about time to reach at least jdk8)

**Comment by aquator** [comment]
Oookay, it looks good now. Remaining issues are warnings due to .txt robot files, and the illegal reflection access warnings of Jython we can't do much about at the moment. I can fix the former too if you'd like. If you could merge and release this, we could use java 11 with robot and maven.

**Comment by Hi-Fi** [comment]
I think this should be released with increased minor number, so this would be 1.5.0 (just to highlight there are so many changes and dropped support for Java 1.7). Could you still do that, so we get first SNAPSHOT also right (as SNAPSHOT is released automatically when merged to develop)?

I think the robot's filename warning can be fixed or left to be fixed later, it's not blocking (yet). Also in the site generation there're deprecation warnings that should be taken care of at some point.

**Comment by pekkaklarck** [comment]
:+1:  for dropping Java 7 support. If someone still needs it, they can use earlier versions. Such changes shouldn't be done in minor releases, though, so good idea to go to 1.5.

Tests should be changed to `*.robot`, but that ought to be topic for a separate PR.

**Pull request merged**
